blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://github.com/BlockCTech/openworking/issues
    about: Search existing issues or ask a general OpenWorking question
